#!/bin/bash
if [ "$1" == "-h" ]; then
  echo "Usage: `basename $0` [Install LDAP Server. Script is invoked using the following command: ./install-ldap-server ; For further help contact cit470.fa2018.team.two@gmail.com]"
  exit 0
fi
