#!/bin/bash
#CIT470 
#Team2

yum -y install nfs-utils
systemctl enable rpcbind
systemctl enable nfs-server
systemctl start rpcbind
systemctl start nfs-server

echo "Backing up home directory files..."
mkdir /tmp/oldhome; cp -aR /home/* /tmp/oldhome
echo "Home directory is Successful backed up with permissions."

#Create primary partition

echo "Creating new primary partition..."	
fdisk /dev/sda <<EOF
p
n
p


w
EOF

partprobe /dev/sda

echo "Partition is succesfully Created."

#Formating partition as an ext3 
mkfs.xfs /dev/sda4 -f
xfs_repair /dev/sda4
echo "Format is Successful completed."

echo " mounting new partition..."
mount /dev/sda4 /home
echo "New partition mounted and named /dev/sda4 on /home"
echo "editing the fstab file..."
echo "/dev/sda4        /home    xfs    defaults    0 0" >> /etc/fstab
echo "Completed." 

echo "Restoring old home directory with permissions."
cp -aR /tmp/oldhome/* /home
echo "home directory is restored."

echo "Editing the exports file..."
echo "/home 10.2.6.0/24(rw,sync,no_root_squash,no_all_squash)" >> /etc/exports
echo "Exporting home directory"
exportfs -a

echo "Configuring firewall."
firewall-cmd --zone=public --add-port=2049/tcp --permanent
firewall-cmd --zone=public --add-port=111/tcp --permanent
firewall-cmd --zone=public --add-port=20048/tcp --permanent
firewall-cmd --zone=public --add-port=2049/udp --permanent
firewall-cmd --zone=public --add-port=111/udp --permanent
firewall-cmd --zone=public --add-port=20048/udp --permanent
firewall-cmd --reload
echo "Firewall is configured"
