#!/bin/bash
#NFS Installation - Project 2
#CIT470-001
#Darci Guriel
#Team 2,Loagn Toler, Keni Patel, Zach Brewers
#10/23/2018

#initiate helper file
if [ "$1" == "-h" ]; then echo "Usage: `basename $0` [Install NFS Server. Script is invoked using the following command: ./install-nfs-server ; For further help contact cit470.fa2018.team.two@gmail.com]" ; exit 0 ; fi >> nfs-install.log 2>&1

#install nfs package, start the services and enable them at boot
echo "Install nfs package and enable the services..." >> nfs-install.log 2>&1 ; yum -y install nfs-utils >> nfs-install.log 2>&1 && systemctl enable rpcbind nfs-server >> nfs-install.log 2>&1 ; systemctl start rpcbind nfs-server >> nfs-install.log 2>&1 && echo "Operation complete." >> nfs-install.log 2>&1

echo "Backing up home directory files..." >> nfs-install.log 2>&1 ; mkdir /tmp/oldhome >> nfs-install.log 2>&1 ; cp -aR /home/* /tmp/oldhome >> nfs-install.log 2>&1 && echo "Home directory is Successful backed up with permissions." >> nfs-install.log 2>&1

#Create primary partition
echo "Creating new primary partition..." >> nfs-install.log 2>&1	
fdisk /dev/sda <<EOF
n
p 


w
EOF
partprobe /dev/sda >> nfs-install.log 2>&1 && echo "Partition is succesfully Created." >> nfs-install.log 2>&1

#Formating partition to XFS
echo "Formatting disk to XFS..." >> nfs-install.log 2>&1 ; mkfs.xfs /dev/sda4 -f  >> nfs-install.log 2>&1 && xfs_repair /dev/sda4 >> nfs-install.log 2>&1 && echo "Format is Successful completed." >> nfs-install.log 2>&1

echo " mounting new partition..." >> nfs-install.log 2>&1 && mount /dev/sda4 /home >> nfs-install.log 2>&1 && echo "New partition mounted and named /dev/sda4 on /home" >> nfs-install.log 2>&1 && echo "editing the fstab file..."  >> nfs-install.log 2>&1 && echo "/dev/sda4        /home    xfs    defaults    0 0" >> /etc/fstab  >> nfs-install.log 2>&1 && echo "Completed." >> nfs-install.log 2>&1

echo "Restoring old home directory with permissions." >> nfs-install.log 2>&1 ; cp -aR /tmp/oldhome/* /home >> nfs-install.log 2>&1 && echo "home directory is restored." >> nfs-install.log 2>&1

echo "Editing the exports file..." >> nfs-install.log 2>&1 ; echo "/home 10.2.6.0/24(rw,sync,no_root_squash,no_all_squash)" >> /etc/exports >> nfs-install.log 2>&1 && echo "Exporting home directory" >> nfs-install.log 2>&1 && exportfs -a >> nfs-install.log 2>&1 && echo "Export complete." >> nfs-install.log 2>&1

echo "Configuring firewall." >> nfs-install.log 2>&1 ; firewall-cmd --zone=public --add-port=2049/tcp --permanent >> nfs-install.log 2>&1 ; firewall-cmd --zone=public --add-port=111/tcp --permanent >> nfs-install.log 2>&1 ; firewall-cmd --zone=public --add-port=20048/tcp --permanent >> nfs-install.log 2>&1 ; firewall-cmd --zone=public --add-port=2049/udp --permanent >> nfs-install.log 2>&1 ; firewall-cmd --zone=public --add-port=111/udp --permanent >> nfs-install.log 2>&1 ; firewall-cmd --zone=public --add-port=20048/udp --permanent >> nfs-install.log 2>&1 && firewall-cmd --reload >> nfs-install.log 2>&1 && echo "Firewall is configured" >> nfs-install.log 2>&1
