#!/bin/bash
#NFS Installation
#Logan Toler, Keni Patel

#initiate helper file using -h
if [ "$1" == "-h" ]; then echo "Usage: `basename $0` [Install NFS Server. Script is invoked using the following command: ./install-nfs-server]" ; exit 0 ; fi | tee -a nfs-install.log

#install nfs package, start the services and enable them at boot
echo "Install nfs package and enable the services..." | tee -a nfs-install.log ; yum -y install nfs-utils >& 1 >> nfs-install.log && systemctl enable rpcbind nfs-server >& 1 >> nfs-install.log ; systemctl start rpcbind nfs-server >& 1 >> nfs-install.log && echo "Operation complete." | tee -a nfs-install.log

#Create primary partition
echo "Creating new primary partition..." | tee -a nfs-install.log	
fdisk /dev/sda <<EOF
n
p 


w
EOF
partprobe /dev/sda >& 1 >> nfs-install.log && echo "Partition is succesfully Created." | tee -a nfs-install.log

#Formating partition to XFS
echo "Formatting disk to XFS..." | tee -a nfs-install.log ; mkfs.xfs /dev/sda4 -f >& 1 >> nfs-install.log && xfs_repair /dev/sda4 >& 1 >> nfs-install.log && echo "Format is Successful completed." | tee -a nfs-install.log

#mounting the newly created partition and automounting it upon system boot
echo " mounting new partition..." | tee -a nfs-install.log && mount /dev/sda4 /home >& 1 >> nfs-install.log && echo "New partition mounted and named /dev/sda4 on /home" | tee -a nfs-install.log && echo "editing the fstab file..." | tee -a nfs-install.log && echo "/dev/sda4        /home    xfs    defaults    0 0" >> /etc/fstab >& 1 >> nfs-install.log && echo "Completed." | tee -a nfs-install.log

#editing exports file to allow access for workstations within the 10.2.6.0/24 range
echo "Editing the exports file..." | tee -a nfs-install.log ; echo "/home 10.2.6.0/24(rw,sync,no_root_squash,no_all_squash)" >> /etc/exports | tee -a nfs-install.log ; echo "Exporting home directory" >& 1 >> nfs-install.log ; exportfs -a  >& 1 >> nfs-install.log && echo "Export complete." | tee -a nfs-install.log

#enabling required NFS ports
echo "Configuring firewall." | tee -a nfs-install.log ; firewall-cmd --zone=public --add-port=2049/tcp --permanent >& 1 >> nfs-install.log ; firewall-cmd --zone=public --add-port=111/tcp --permanent >& 1 >> nfs-install.log ; firewall-cmd --zone=public --add-port=20048/tcp --permanent >& 1 >> nfs-install.log ; firewall-cmd --zone=public --add-port=2049/udp --permanent >& 1 >> nfs-install.log ; firewall-cmd --zone=public --add-port=111/udp --permanent >& 1 >> nfs-install.log ; firewall-cmd --zone=public --add-port=20048/udp --permanent >& 1 >> nfs-install.log && firewall-cmd --reload >& 1 >> nfs-install.log && echo "Firewall is configured" | tee -a nfs-install.log
